# Generated by Django 3.2.25 on 2024-07-17 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalModerationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested', models.DateTimeField()),
                ('approved', models.DateTimeField(blank=True, null=True)),
                ('denied', models.DateTimeField(blank=True, null=True)),
                ('timed_out', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(max_length=1048576)),
                ('response', models.TextField(blank=True, max_length=1048576, null=True)),
                ('requester_id', models.CharField(default='unknown-requester', max_length=1024)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_dialog_approvals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
