# Generated by Django 3.2.25 on 2024-07-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dialog_engine_moderation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalmoderationrequest',
            name='used',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
