# pylint: skip-file
# Generated by Django 5.2.4 on 2025-08-06 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('simple_moderation', '0002_externalmoderationrequest_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderator_id', models.CharField(max_length=1024, unique=True)),
                ('moderator_for', models.TextField(default='*', max_length=4194304)),
                ('active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict, max_length=4194304)),
            ],
        ),
        migrations.RemoveField(
            model_name='externalmoderationrequest',
            name='moderator',
        ),
        migrations.CreateModel(
            name='ModerationDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=True)),
                ('decision_maker', models.CharField(max_length=1024)),
                ('when', models.DateTimeField()),
                ('metadata', models.TextField(blank=True, max_length=4194304, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='simple_moderation.externalmoderationrequest')),
            ],
        ),
    ]
