# pylint: skip-file
# Generated by Django 5.2.4 on 2025-08-06 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_moderation', '0003_moderator_remove_externalmoderationrequest_moderator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalmoderationrequest',
            name='response',
        ),
    ]
