# pylint: skip-file
# Generated by Django 5.2.4 on 2025-08-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_moderation', '0004_remove_externalmoderationrequest_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalmoderationrequest',
            name='response',
            field=models.TextField(blank=True, max_length=1048576, null=True),
        ),

        migrations.AddField(
            model_name='externalmoderationrequest',
            name='automatic_decision',
            field=models.BooleanField(default=False),
        ),
    ]
